import { AchievementDefinition } from '../types/achievements';

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: 'first_habit_log',
    title: 'First Intentional Check-In',
    description: 'Complete your first habit log.',
    category: 'habits',
    tier: 'bronze',
    metric: 'totalHabitCompletions',
    target: 1,
    icon: 'CheckCircle',
    color: '#10b981',
    rewardText: 'A small action is now visible momentum.',
  },
  {
    id: 'habit_25_completions',
    title: 'Rhythm Builder',
    description: 'Complete 25 habit logs.',
    category: 'habits',
    tier: 'silver',
    metric: 'totalHabitCompletions',
    target: 25,
    icon: 'Dumbbell',
    color: '#22c55e',
    rewardText: 'You are turning intention into repetition.',
  },
  {
    id: 'habit_100_completions',
    title: 'Identity in Motion',
    description: 'Complete 100 habit logs.',
    category: 'habits',
    tier: 'gold',
    metric: 'totalHabitCompletions',
    target: 100,
    icon: 'Medal',
    color: '#f59e0b',
    rewardText: 'Your calendar now carries proof of who you are becoming.',
  },
  {
    id: 'build_streak_7',
    title: 'Seven-Day Flame',
    description: 'Reach a 7-day streak on a build habit.',
    category: 'streaks',
    tier: 'silver',
    metric: 'bestBuildHabitStreak',
    target: 7,
    icon: 'Flame',
    color: '#f97316',
    rewardText: 'Your good habit is now warm enough to protect.',
  },
  {
    id: 'build_streak_30',
    title: 'Thirty-Day Forge',
    description: 'Reach a 30-day streak on a build habit.',
    category: 'streaks',
    tier: 'legend',
    metric: 'bestBuildHabitStreak',
    target: 30,
    icon: 'Flame',
    color: '#fb7185',
    rewardText: 'This is no longer a task. It is part of your system.',
  },
  {
    id: 'quit_streak_7',
    title: 'Clean Week Shield',
    description: 'Reach 7 relapse-free days on a quit habit.',
    category: 'streaks',
    tier: 'silver',
    metric: 'bestQuitHabitStreak',
    target: 7,
    icon: 'Shield',
    color: '#8b5cf6',
    rewardText: 'Restraint is becoming visible strength.',
  },
  {
    id: 'quit_streak_30',
    title: 'Thirty-Day Reset',
    description: 'Reach 30 relapse-free days on a quit habit.',
    category: 'streaks',
    tier: 'legend',
    metric: 'bestQuitHabitStreak',
    target: 30,
    icon: 'ShieldCheck',
    color: '#a855f7',
    rewardText: 'You are proving that old loops can be redesigned.',
  },
  {
    id: 'work_cards_5',
    title: 'Planner Spark',
    description: 'Create 5 work cards.',
    category: 'planning',
    tier: 'bronze',
    metric: 'totalWorkCardsCreated',
    target: 5,
    icon: 'LayoutList',
    color: '#06b6d4',
    rewardText: 'Your work is becoming concrete before it competes for attention.',
  },
  {
    id: 'work_cards_completed_10',
    title: 'Finisher',
    description: 'Complete 10 work cards.',
    category: 'work',
    tier: 'gold',
    metric: 'totalWorkCardsCompleted',
    target: 10,
    icon: 'BadgeCheck',
    color: '#3b82f6',
    rewardText: 'Planned outcomes are becoming finished outcomes.',
  },
  {
    id: 'work_hours_10',
    title: 'Deep Work Reserve',
    description: 'Log 10 total hours of work sessions.',
    category: 'work',
    tier: 'silver',
    metric: 'totalWorkHours',
    target: 10,
    icon: 'Briefcase',
    color: '#2563eb',
    rewardText: 'Your attention is being invested, not leaked.',
  },
  {
    id: 'reading_days_7',
    title: 'Seven Reading Days',
    description: 'Record reading progress on 7 days.',
    category: 'reading',
    tier: 'silver',
    metric: 'readingDays',
    target: 7,
    icon: 'BookOpen',
    color: '#8b5cf6',
    rewardText: 'You are replacing passive feed loops with chosen inputs.',
  },
  {
    id: 'reading_minutes_300',
    title: 'Five-Hour Library',
    description: 'Log 300 minutes of reading.',
    category: 'reading',
    tier: 'gold',
    metric: 'totalReadingMinutes',
    target: 300,
    icon: 'BookMarked',
    color: '#7c3aed',
    rewardText: 'Your future self is being fed better material.',
  },
  {
    id: 'under_limit_7_days',
    title: 'Budget Guardian',
    description: 'Stay under your screen-time limit on 7 tracked days.',
    category: 'screen_time',
    tier: 'silver',
    metric: 'daysUnderScreenLimit',
    target: 7,
    icon: 'TimerReset',
    color: '#14b8a6',
    rewardText: 'You are budgeting attention before the day spends it for you.',
  },
  {
    id: 'doomscroll_free_today',
    title: 'Feed Breaker',
    description: 'Keep doomscroll-risk apps below 10 minutes today.',
    category: 'screen_time',
    tier: 'bronze',
    metric: 'doomscrollFreeToday',
    target: 1,
    icon: 'Sparkles',
    color: '#ec4899',
    rewardText: 'You interrupted the feed before it captured the day.',
  },
  {
    id: 'apps_80_configured',
    title: 'Intentional App Library',
    description: 'Classify 80% of installed apps for wellbeing scoring.',
    category: 'planning',
    tier: 'gold',
    metric: 'configuredAppPercent',
    target: 80,
    icon: 'SlidersHorizontal',
    color: '#06b6d4',
    rewardText: 'Your tools now have assigned roles instead of hidden influence.',
  },
  {
    id: 'intentional_day',
    title: 'Intentional Day',
    description: 'Complete habits, log work, and keep doomscrolling low today.',
    category: 'planning',
    tier: 'legend',
    metric: 'intentionalTodayScore',
    target: 3,
    icon: 'Trophy',
    color: '#facc15',
    rewardText: 'This is the shape of an intentional day.',
  },
];
