import { AchievementDefinition, AchievementTier } from '../types/achievements';

export const ACHIEVEMENT_LAYER_COLORS: Record<AchievementTier, string> = {
  layer_1: '#22c55e',
  layer_2: '#06b6d4',
  layer_3: '#3b82f6',
  layer_4: '#8b5cf6',
  layer_5: '#d946ef',
  layer_6: '#f97316',
  layer_7: '#f59e0b',
  layer_8: '#ef4444',
  layer_9: '#facc15',
};

export const ACHIEVEMENT_LAYER_LABELS: Record<AchievementTier, string> = {
  layer_1: 'Layer 1',
  layer_2: 'Layer 2',
  layer_3: 'Layer 3',
  layer_4: 'Layer 4',
  layer_5: 'Layer 5',
  layer_6: 'Layer 6',
  layer_7: 'Layer 7',
  layer_8: 'Layer 8',
  layer_9: 'Layer 9',
};

function achievement(definition: Omit<AchievementDefinition, 'color'>): AchievementDefinition {
  return { ...definition, color: ACHIEVEMENT_LAYER_COLORS[definition.tier] };
}

export const ACHIEVEMENTS: AchievementDefinition[] = [
  achievement({
    id: 'first_habit_log',
    title: 'First Intentional Check-In',
    description: 'Complete your first habit log.',
    category: 'habits',
    tier: 'layer_1',
    metric: 'totalHabitCompletions',
    target: 1,
    icon: 'CheckCircle',
    rewardText: 'A small action is now visible momentum.',
  }),
  achievement({
    id: 'first_work_card',
    title: 'First Planned Outcome',
    description: 'Create your first work card.',
    category: 'planning',
    tier: 'layer_1',
    metric: 'totalWorkCardsCreated',
    target: 1,
    icon: 'LayoutList',
    rewardText: 'Your work has a shape before it competes for attention.',
  }),
  achievement({
    id: 'intentional_day',
    title: 'Intentional Day',
    description: 'Complete habits, log work, and keep doomscrolling low today.',
    category: 'planning',
    tier: 'layer_1',
    metric: 'intentionalTodayScore',
    target: 3,
    icon: 'Trophy',
    rewardText: 'This is the shape of an intentional day.',
  }),
  achievement({
    id: 'habit_25_completions',
    title: 'Rhythm Builder',
    description: 'Complete 25 habit logs.',
    category: 'habits',
    tier: 'layer_2',
    metric: 'totalHabitCompletions',
    target: 25,
    icon: 'Dumbbell',
    rewardText: 'You are turning intention into repetition.',
  }),
  achievement({
    id: 'build_streak_7',
    title: 'Seven-Day Flame',
    description: 'Reach a 7-day streak on a build habit.',
    category: 'streaks',
    tier: 'layer_2',
    metric: 'bestBuildHabitStreak',
    target: 7,
    icon: 'Flame',
    rewardText: 'Your good habit is now warm enough to protect.',
  }),
  achievement({
    id: 'work_cards_5',
    title: 'Planner Spark',
    description: 'Create 5 work cards.',
    category: 'planning',
    tier: 'layer_2',
    metric: 'totalWorkCardsCreated',
    target: 5,
    icon: 'LayoutList',
    rewardText: 'Your future work is becoming concrete.',
  }),
  achievement({
    id: 'quit_streak_7',
    title: 'Clean Week Shield',
    description: 'Reach 7 relapse-free days on a quit habit.',
    category: 'streaks',
    tier: 'layer_3',
    metric: 'bestQuitHabitStreak',
    target: 7,
    icon: 'Shield',
    rewardText: 'Restraint is becoming visible strength.',
  }),
  achievement({
    id: 'reading_days_7',
    title: 'Seven Reading Days',
    description: 'Record reading progress on 7 days.',
    category: 'reading',
    tier: 'layer_3',
    metric: 'readingDays',
    target: 7,
    icon: 'BookOpen',
    rewardText: 'You are replacing passive feed loops with chosen inputs.',
  }),
  achievement({
    id: 'under_limit_7_days',
    title: 'Budget Guardian',
    description: 'Stay under your screen-time limit on 7 tracked days.',
    category: 'screen_time',
    tier: 'layer_3',
    metric: 'daysUnderScreenLimit',
    target: 7,
    icon: 'TimerReset',
    rewardText: 'You are budgeting attention before the day spends it for you.',
  }),
  achievement({
    id: 'work_cards_completed_10',
    title: 'Finisher',
    description: 'Complete 10 work cards.',
    category: 'work',
    tier: 'layer_4',
    metric: 'totalWorkCardsCompleted',
    target: 10,
    icon: 'BadgeCheck',
    rewardText: 'Planned outcomes are becoming finished outcomes.',
  }),
  achievement({
    id: 'work_hours_10',
    title: 'Deep Work Reserve',
    description: 'Log 10 total hours of work sessions.',
    category: 'work',
    tier: 'layer_4',
    metric: 'totalWorkHours',
    target: 10,
    icon: 'Briefcase',
    rewardText: 'Your attention is being invested, not leaked.',
  }),
  achievement({
    id: 'apps_80_configured',
    title: 'Intentional App Library',
    description: 'Classify 80% of installed apps for wellbeing scoring.',
    category: 'planning',
    tier: 'layer_4',
    metric: 'configuredAppPercent',
    target: 80,
    icon: 'SlidersHorizontal',
    rewardText: 'Your tools now have assigned roles instead of hidden influence.',
  }),
  achievement({
    id: 'habit_100_completions',
    title: 'Identity in Motion',
    description: 'Complete 100 habit logs.',
    category: 'habits',
    tier: 'layer_5',
    metric: 'totalHabitCompletions',
    target: 100,
    icon: 'Medal',
    rewardText: 'Your calendar now carries proof of who you are becoming.',
  }),
  achievement({
    id: 'build_streak_30',
    title: 'Thirty-Day Forge',
    description: 'Reach a 30-day streak on a build habit.',
    category: 'streaks',
    tier: 'layer_5',
    metric: 'bestBuildHabitStreak',
    target: 30,
    icon: 'Flame',
    rewardText: 'This is no longer a task. It is part of your system.',
  }),
  achievement({
    id: 'quit_streak_30',
    title: 'Thirty-Day Reset',
    description: 'Reach 30 relapse-free days on a quit habit.',
    category: 'streaks',
    tier: 'layer_5',
    metric: 'bestQuitHabitStreak',
    target: 30,
    icon: 'ShieldCheck',
    rewardText: 'You are proving that old loops can be redesigned.',
  }),
  achievement({
    id: 'reading_minutes_300',
    title: 'Five-Hour Library',
    description: 'Log 300 minutes of reading.',
    category: 'reading',
    tier: 'layer_6',
    metric: 'totalReadingMinutes',
    target: 300,
    icon: 'BookMarked',
    rewardText: 'Your future self is being fed better material.',
  }),
  achievement({
    id: 'work_hours_50',
    title: 'Attention Investor',
    description: 'Log 50 total hours of work sessions.',
    category: 'work',
    tier: 'layer_6',
    metric: 'totalWorkHours',
    target: 50,
    icon: 'Briefcase',
    rewardText: 'You are compounding focused hours into a life direction.',
  }),
  achievement({
    id: 'under_limit_30_days',
    title: 'Thirty-Day Steward',
    description: 'Stay under your screen-time limit on 30 tracked days.',
    category: 'screen_time',
    tier: 'layer_7',
    metric: 'daysUnderScreenLimit',
    target: 30,
    icon: 'TimerReset',
    rewardText: 'Attention stewardship is becoming a lifestyle pattern.',
  }),
  achievement({
    id: 'habit_365_completions',
    title: 'Year of Reps',
    description: 'Complete 365 habit logs.',
    category: 'habits',
    tier: 'layer_7',
    metric: 'totalHabitCompletions',
    target: 365,
    icon: 'Medal',
    rewardText: 'Your daily reps have become a long arc of evidence.',
  }),
  achievement({
    id: 'build_streak_90',
    title: 'Ninety-Day Keystone',
    description: 'Reach a 90-day streak on a build habit.',
    category: 'streaks',
    tier: 'layer_8',
    metric: 'bestBuildHabitStreak',
    target: 90,
    icon: 'Flame',
    rewardText: 'A good habit has become structural support.',
  }),
  achievement({
    id: 'time_stewardship_9',
    title: 'Time Stewardship IX',
    description: 'Stay under your screen-time limit on 90 tracked days.',
    category: 'screen_time',
    tier: 'layer_9',
    metric: 'daysUnderScreenLimit',
    target: 90,
    icon: 'Sparkles',
    rewardText: 'Your time is no longer drifting. It is being stewarded.',
  }),
];
